before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: sEBJu6QcIWdsvEZc0CnFVuzHPcOA8Oo1lSEKRZpxwRT4B6SznFD0/ORZMB9nDgMT0FUq1+I7HB4VF6R+ZXsno37iRU/plLlVEjX5XzDfWURS20/ccmJOuDExYbHcg+Mk4FnpZRlZvFsQqP+kT+6XyvT9zCQseuNQXySv3sepHtadeL0L+rtK0m3MWiESDFLN9ahnn/hts4UZcYBwBdir+cg2Jh4DlESpuc5c96xAjB6jXEfFoz3Yyh44WPCxT8b5gE5rMU/nwSunCrjJy36bmTB1j15M0L4f8PsBQuG9wQNfDK4nth43Sermj+fHOHwpvkzopU7g2BRQhW4lJ/wEGphauoz+Aef90DWGCBc+10QqUATp3ZU8nIo+R22nlb7gGrOwKdQ7YJEeL4vMMZ09/cJS59ROxWyDIhTs22/DtSbvdI+AfAWkTfX+8yxIeHpz14uxtWHEzKSaC0iFn/1OoLbXxzKokJ/gcdhgHnfUV9aQTdd1zsRodVpG8idWV8P3O3hstTXLSq1SRJDgDZITOxFQ8fH83t1QfOEeLVHE7zzRySDRID06bFpALa8yfphIMPFE3QwuLJSYge9eCA6b8r3cTfbJiF60qWqzZGlAns2e0FX4U3RraQ8csV+QYVlBf55qf2dlQwLZZFd6X81vSBPfbhIuMb6sEMa3bU9BBBI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
